### ISSUE TITLE
Connecting a creative motor to a machine crashes with "Index 0 out of bounds for length 0"

### ISSUE THREAD

**Issue by abruncke** [foxynotail/create-storage-mod-fabric#24]
I have a test level with just a few create machines on it.  I am building a new one and have all the belts and funnels laid out.  I connect a creative motor to it to fire it up and test it out and the game crashes.  The level is now corrupted and cannot be loaded again.  I have reduced all my mods to only 3 and identified that without Create: Storage the there is no crash.  I have tried this on a brand new map and it seems that as soon as a belt and connected objects becomes "live" something is happening.

I am running a Fabric 1.20.1 single player world with create 0.5.1-f-build.1417 and fxntstorage-0.20-1.20.1-FABRIC+1.20.1.

Crash report below:
----------------------

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-09-23 08:55:44
Description: Ticking block entity

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.createWrapperList(SidedInventoryStorageImpl.java:53)
	at net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.<init>(SidedInventoryStorageImpl.java:38)
	at net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.getSidedWrapper(InventoryStorageImpl.java:110)
	at net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.of(InventoryStorageImpl.java:65)
	at net.fabricmc.fabric.api.transfer.v1.item.InventoryStorage.of(InventoryStorage.java:66)
	at net.fabricmc.fabric.api.transfer.v1.item.ItemStorage.lambda$static$2(ItemStorage.java:134)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiCacheImpl.find(BlockApiCacheImpl.java:95)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.CapManipulationBehaviourBase.getInventory(CapManipulationBehaviourBase.java:65)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.CapManipulationBehaviourBase.hasInventory(CapManipulationBehaviourBase.java:58)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.VersionedInventoryTrackerBehaviour.stillWaiting(VersionedInventoryTrackerBehaviour.java:23)
	at com.simibubi.create.content.logistics.funnel.FunnelBlockEntity.activateExtractingBeltFunnel(FunnelBlockEntity.java:201)
	at com.simibubi.create.content.logistics.funnel.FunnelBlockEntity.tick(FunnelBlockEntity.java:112)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.createWrapperList(SidedInventoryStorageImpl.java:53)
	at net.fabricmc.fabric.impl.transfer.item.SidedInventoryStorageImpl.<init>(SidedInventoryStorageImpl.java:38)
	at net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.getSidedWrapper(InventoryStorageImpl.java:110)
	at net.fabricmc.fabric.impl.transfer.item.InventoryStorageImpl.of(InventoryStorageImpl.java:65)
	at net.fabricmc.fabric.api.transfer.v1.item.InventoryStorage.of(InventoryStorage.java:66)
	at net.fabricmc.fabric.api.transfer.v1.item.ItemStorage.lambda$static$2(ItemStorage.java:134)
	at net.fabricmc.fabric.impl.lookup.block.BlockApiCacheImpl.find(BlockApiCacheImpl.java:95)
	at net.fabricmc.fabric.api.lookup.v1.block.BlockApiCache.find(BlockApiCache.java:55)
	at io.github.fabricators_of_create.porting_lib.util.StorageProvider$CachedStorageProvider.get(StorageProvider.java:116)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.CapManipulationBehaviourBase.getInventory(CapManipulationBehaviourBase.java:65)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.CapManipulationBehaviourBase.hasInventory(CapManipulationBehaviourBase.java:58)
	at com.simibubi.create.foundation.blockEntity.behaviour.inventory.VersionedInventoryTrackerBehaviour.stillWaiting(VersionedInventoryTrackerBehaviour.java:23)
	at com.simibubi.create.content.logistics.funnel.FunnelBlockEntity.activateExtractingBeltFunnel(FunnelBlockEntity.java:201)
	at com.simibubi.create.content.logistics.funnel.FunnelBlockEntity.tick(FunnelBlockEntity.java:112)
	at com.simibubi.create.foundation.blockEntity.SmartBlockEntityTicker.tick(SmartBlockEntityTicker.java:15)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)

-- Block entity being ticked --
Details:
	Name: create:funnel // com.simibubi.create.content.logistics.funnel.FunnelBlockEntity
	Block: Block{create:andesite_belt_funnel}[facing=north,powered=false,shape=retracted,waterlogged=false]
	Block location: World: (70,4,-33), Section: (at 6,4,15 in 4,0,-3; chunk contains blocks 64,-64,-48 to 79,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Block: Block{create:andesite_belt_funnel}[facing=north,powered=false,shape=retracted,waterlogged=false]
	Block location: World: (70,4,-33), Section: (at 6,4,15 in 4,0,-3; chunk contains blocks 64,-64,-48 to 79,319,-33), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:662)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:716)
	at net.minecraft.class_1937.method_18471(class_1937.java:470)
	at net.minecraft.class_3218.method_18765(class_3218.java:390)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['xxxxxxxx'/115, l='ServerLevel[Test - Machines placed]', x=73.12, y=4.44, z=-39.61]]
	Chunk stats: 4225
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,0,0), Section: (at 0,0,0 in 0,0,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 47377 game time, 9000 day time
	Level name: Test - Machines placed
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Known server brands: fabric
	Removed feature flags: 
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.class_1132.method_3748(class_1132.java:105)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 3037230736 bytes (2896 MiB) / 4630511616 bytes (4416 MiB) up to 53687091200 bytes (51200 MiB)
	CPUs: 20
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 85 Stepping 7
	Microarchitecture: Cascade Lake
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 10
	Number of logical CPUs: 20
	Graphics card #0 name: NVIDIA GeForce RTX 3080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2206
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5241
	Memory slot #0 capacity (MB): 16384.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 16384.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 16384.00
	Memory slot #2 clockSpeed (GHz): 3.20
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 16384.00
	Memory slot #3 clockSpeed (GHz): 3.20
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 69341.07
	Virtual memory used (MB): 32086.59
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 28.46
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx50G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		create: Create 0.5.1-f-build.1417+mc1.20.1
			com_electronwill_night-config_core: core 3.6.6
			com_electronwill_night-config_toml: toml 3.6.6
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.10-2
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.3.2+1.20.1
			porting_lib_base: Porting Lib Base 2.3.2+1.20.1
				porting_lib_config: Porting Lib Config 2.3.2+1.20.1
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.3.2+1.20.1
				porting_lib_utility: Porting Lib Utility 2.3.2+1.20.1
			porting_lib_brewing: Porting Lib Brewing 2.3.2+1.20.1
			porting_lib_client_events: Porting Lib Client Events 2.3.2+1.20.1
			porting_lib_entity: Porting Lib Entity 2.3.2+1.20.1
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.3.2+1.20.1
			porting_lib_extensions: Porting Lib Extensions 2.3.2+1.20.1
				porting_lib_attributes: Porting Lib Attributes 2.3.2+1.20.1
				porting_lib_common: Porting Lib Common 2.3.2+1.20.1
			porting_lib_models: Porting Lib Models 2.3.2+1.20.1
			porting_lib_networking: Porting Lib Networking 2.3.2+1.20.1
				porting_lib_core: Porting Lib Core 2.3.2+1.20.1
			porting_lib_obj_loader: Porting Lib Obj Loader 2.3.2+1.20.1
				porting_lib_model_loader: Porting Lib Model Loader 2.3.2+1.20.1
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.3.2+1.20.1
			porting_lib_transfer: Porting Lib Transfer 2.3.2+1.20.1
				porting_lib_fluids: Porting Lib Fluids 2.3.2+1.20.1
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_gametest: Porting Lib GameTest 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		fabric-api: Fabric API 0.92.2+1.20.1
			fabric-api-base: Fabric API Base 0.4.31+1802ada577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.36+1802ada577
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.13+1802ada577
			fabric-block-api-v1: Fabric Block API (v1) 1.0.11+1802ada577
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.1+1802ada577
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.41+1802ada577
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.2+1802ada577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.34+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.13+1802ada577
			fabric-commands-v0: Fabric Commands (v0) 0.2.51+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.64+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.11+1802ada577
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.5+1802ada577
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.19+1802ada577
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.0.0+de0fd6d177
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.4+1802ada577
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.54+1802ada577
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.0+1c78457f77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.2+1802ada577
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.63+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.40+1802ada577
			fabric-item-api-v1: Fabric Item API (v1) 2.1.28+1802ada577
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.12+1802ada577
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.37+1802ada577
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.35+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.22+1802ada577
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.1+1802ada577
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.45+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.9+1802ada577
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.50+1802ada577
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.3+1802ada577
			fabric-models-v0: Fabric Models (v0) 0.4.2+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.11+1802ada577
			fabric-networking-v0: Fabric Networking (v0) 0.3.51+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.3+1802ada577
			fabric-particles-v1: Fabric Particles (v1) 1.1.2+1802ada577
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.21+1802ada577
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.3+1802ada577
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.1+1802ada577
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.2+85287f9f77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.46+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.37+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.28+1802ada577
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.49+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.8+1802ada577
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.8+1802ada577
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.10+1802ada577
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.8+1802ada577
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.30+1802ada577
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.13+1802ada577
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.5+8dd72ea377
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.1+1802ada577
		fabricloader: Fabric Loader 0.16.3
			mixinextras: MixinExtras 0.4.1
		fxntstorage: Create: Storage 0.20-1.20.1-FABRIC+1.20.1
		java: OpenJDK 64-Bit Server VM 17
		minecraft: Minecraft 1.20.1
	Flywheel Backend: GL33 Instanced Arrays
	Server Running: true
	Player Count: 1 / 8; [class_3222['Wile_E_One'/115, l='ServerLevel[Test - Machines placed]', x=73.12, y=4.44, z=-39.61]]
	Data Packs: vanilla, fabric, file/AllMobHeads_V7.3.1.zip, file/Statue.zip (incompatible), file/afk display v1.1.7 (MC 1.20-1.20.6).zip, file/anti enderman grief v1.1.7 (MC 1.20-1.20.6).zip, file/armor statues v2.8.12 (MC 1.20-1.20.6).zip, file/custom nether portals v2.3.10 (MC 1.20-1.20.6).zip, file/double shulker shells v1.3.7 (MC 1.20-1.20.6).zip, file/dragon drops v1.3.7 (MC 1.20-1.20.6).zip, file/more mob heads v2.13.0 (MC 1.20-1.20.6).zip, file/player head drops v1.1.7 (MC 1.20-1.20.6).zip, file/silence mobs v1.2.2 (MC 1.20-1.20.6).zip, file/spectator conduit power v1.1.7 (MC 1.20-1.20.6).zip, file/spectator night vision v1.1.7 (MC 1.20-1.20.6).zip, file/track raw statistics v1.7.3 (MC 1.20-1.20.6).zip, file/track statistics v1.1.9 (MC 1.20-1.20.6).zip, file/villager workstation highlights v1.1.7 (MC 1.20-1.20.6).zip, file/wandering trades v1.7.4 (MC 1.20-1.20.6).zip
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Launched Version: fabric-loader-0.16.3-1.20.1

**Comment by tivvo** [comment]
bump, geting this too and i can't really fix it

**Comment by uberswe** [comment]
I can reproduce this by setting up a bunch of storage boxes with funnels that are always inputting and outputting items, then make a schematic of this while it's running, when pasting the schematic you will be chunk banned. Players have also managed to cause multiple chunk bans on servers I run and we have to delete the items using the /fill command or simply remove the chunk using MCA Selector.
